apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-copilot-backend
  title: "@backstage-community/plugin-copilot-backend"
  description: Backend plugin that ingests and stores GitHub Copilot usage metrics for organization and enterprise reporting.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/copilot/plugins/copilot-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.1.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
