apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-plugin-topology-dev-backend
  title: "@internal/plugin-topology-dev-backend"
  description: Internal backend plugin scaffold used for local development of the Topology plugin.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/topology/plugins/topology-dev-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.0.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
