apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-graph
  title: "@backstage/plugin-catalog-graph"
  description: Frontend plugin that visualizes relations, such as ownership and APIs, between catalog entities via cards and a graph page.
  tags:
    - frontend-plugin
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/catalog-graph
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.6.8-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
