apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-tech-radar-backend
  title: "@backstage-community/plugin-tech-radar-backend"
  description: Backend plugin that fetches Tech Radar response data from a configured URL and serves it to the tech-radar frontend plugin.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/tech-radar/plugins/tech-radar-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.21.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
