apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: seatgeek-backstage-plugin-aws-catalog-common
  title: "@seatgeek/backstage-plugin-aws-catalog-common"
  description: Common functionality for AWS catalog providers
  tags:
    - common-library
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: seatgeek/backstage-plugins
    backstage.io/source-location: url:https://github.com/seatgeek/backstage-plugins/tree/HEAD/plugins/aws-catalog-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.0.0-semantically-released
  links:
    - url: https://github.com/seatgeek/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: common-library
  lifecycle: unknown
  owner: seatgeek
