apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-quickstart-2
  title: "@red-hat-developer-hub/backstage-plugin-quickstart"
  description: Frontend plugin that shows a guided onboarding drawer with interactive quickstart steps and progress tracking for new Red Hat Developer Hub users.
  tags:
    - frontend-plugin
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/quickstart/plugins/quickstart
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 2.0.1
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: redhat-developer
