apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secustor-backstage-plugin-renovate-backend
  title: "@secustor/backstage-plugin-renovate-backend"
  description: Backend plugin that runs Renovate against GitHub, GitLab, and Bitbucket Server repositories and extracts dependency reports.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: secustor/backstage-plugins
    backstage.io/source-location: url:https://github.com/secustor/backstage-plugins/tree/HEAD/plugins/renovate-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.19.0
  links:
    - url: https://github.com/secustor/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: secustor
