apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-explore-backend
  title: "@backstage-community/plugin-explore-backend"
  description: Backend service exposing organization tools to the Explore frontend plugin and providing a search collator to index them.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/explore/plugins/explore-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.16.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
