apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-search-backend-module-techdocs
  title: "@backstage/plugin-search-backend-module-techdocs"
  description: A module for the search backend that exports techdocs modules
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/search-backend-module-techdocs
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.4.18-next.2
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
