apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-todo-backend
  title: "@backstage-community/plugin-todo-backend"
  description: A Backstage backend plugin that lets you browse TODO comments in your source code
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/todo/plugins/todo-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.25.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
