apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-acr
  title: "@backstage-community/plugin-acr"
  description: A Backstage plugin that displays information about your container images available in the Azure Container Registry
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/acr/plugins/acr
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.28.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
