apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-scorecard-backend-modu-7
  title: "@red-hat-developer-hub/backstage-plugin-scorecard-backend-module-jira"
  description: The jira backend module for the scorecard plugin.
  tags:
    - backend-plugin-module
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/scorecard/plugins/scorecard-backend-module-jira
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 4.2.0
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: redhat-developer
