apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-connections-example-backend
  title: "@backstage/plugin-connections-example-backend"
  description: Example backend plugin scaffolded by the Backstage CLI, meant as a starting template for a plugin backend.
  tags:
    - backend-plugin
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/connections-example-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.1.4-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
