apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pagerduty-backstage-plugin-backend
  title: "@pagerduty/backstage-plugin-backend"
  description: Backend plugin that powers the PagerDuty frontend plugin, adding security and configuration for PagerDuty integration.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: PagerDuty/backstage-plugins
    backstage.io/source-location: url:https://github.com/PagerDuty/backstage-plugins/tree/HEAD/plugins/backstage-plugin-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.14.0
  links:
    - url: https://github.com/PagerDuty/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://pagerduty.github.io/backstage-plugin-docs/index.html
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: pagerduty
