apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-manage-backend
  title: "@backstage-community/plugin-manage-backend"
  description: Backend that fetches a user's owner groups and all entities owned by that user or their groups, with an optional MCP action.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/manage/plugins/manage-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.6.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
