apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-boost-backend-module-kag
  title: "@red-hat-developer-hub/backstage-plugin-boost-backend-module-kagenti"
  description: Kagenti provider module for the boost AI platform
  tags:
    - backend-plugin-module
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/boost/plugins/boost-backend-module-kagenti
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.1.7
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: redhat-developer
