apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadiehq-scaffolder-backend-module-aws
  title: "@roadiehq/scaffolder-backend-module-aws"
  description: Scaffolder backend module with actions for AWS S3 copy, ECR repository creation, and Secrets Manager secret creation.
  tags:
    - backend-plugin-module
    - repo-roadie-backstage-plugins
  annotations:
    github.com/project-slug: RoadieHQ/roadie-backstage-plugins
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/HEAD/plugins/scaffolder-actions/scaffolder-backend-module-aws
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 2.8.2
  links:
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: roadiehq
