apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-mcp-chat
  title: "@backstage-community/plugin-mcp-chat"
  description: A Backstage plugin that provides a chat interface for interacting with the MCP Servers.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/mcp-chat/plugins/mcp-chat
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.10.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://github.com/backstage/community-plugins/tree/main/workspaces/mcp-chat/plugins/mcp-chat
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
