apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: oasis9217-backstage-plugin-ibm-auth-backend
  title: "@oasis9217/backstage-plugin-ibm-auth-backend"
  description: Backstage plugin for authentication with IBM Security Verify
  tags:
    - backend-plugin
    - repo-backstage-plugin-ibm-auth
  annotations:
    github.com/project-slug: songhui-ryu/backstage-plugin-ibm-auth
    backstage.io/source-location: url:https://github.com/songhui-ryu/backstage-plugin-ibm-auth/tree/HEAD/packages/ibm-auth-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.0.1
  links:
    - url: https://github.com/songhui-ryu/backstage-plugin-ibm-auth
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: songhui-ryu
