apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-konflux-backend
  title: "@red-hat-developer-hub/backstage-plugin-konflux-backend"
  description: Backend plugin that fetches and aggregates Konflux Kubernetes resources across multiple clusters and namespaces for the Konflux frontend.
  tags:
    - backend-plugin
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/konflux/plugins/konflux-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.2.1
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: redhat-developer
