apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rootly-backstage-plugin-entity-processor
  title: "@rootly/backstage-plugin-entity-processor"
  description: Rootly Catalog processor Backstage
  tags:
    - backend-plugin-module
    - repo-backstage-plugin-entity-processor
  annotations:
    github.com/project-slug: rootlyhq/backstage-plugin-entity-processor
    backstage.io/source-location: url:https://github.com/rootlyhq/backstage-plugin-entity-processor/tree/HEAD
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 1.3.2
  links:
    - url: https://github.com/rootlyhq/backstage-plugin-entity-processor
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: rootlyhq
