apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: axis-backstage-plugin-vacation-calendar
  title: "@axis-backstage/plugin-vacation-calendar"
  description: Frontend plugin that shows colleagues' vacations and out-of-office events by fetching calendars via the Microsoft Graph API.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: AxisCommunications/backstage-plugins
    backstage.io/source-location: url:https://github.com/AxisCommunications/backstage-plugins/tree/HEAD/plugins/vacation-calendar
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.11.4
  links:
    - url: https://github.com/AxisCommunications/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: axiscommunications
