apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadiehq-rag-ai-backend-embeddings-aws
  title: "@roadiehq/rag-ai-backend-embeddings-aws"
  description: The AWS (Bedrock) backend module for the @roadiehq/rag-ai plugin.
  tags:
    - backend-plugin-module
    - repo-roadie-backstage-plugins
  annotations:
    github.com/project-slug: RoadieHQ/roadie-backstage-plugins
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/HEAD/plugins/backend/rag-ai-backend-embeddings-aws
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 2.1.0
  links:
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: roadiehq
