apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-multi-source-security-viewer
  title: "@backstage-community/plugin-multi-source-security-viewer"
  description: Frontend plugin that aggregates and visualizes pipeline security scan results from multiple CI providers on the entity page.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/multi-source-security-viewer/plugins/multi-source-security-viewer
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.0.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
