apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-graphiql
  title: "@backstage-community/plugin-graphiql"
  description: Backstage plugin for browsing GraphQL APIs
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/graphiql/plugins/graphiql
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.19.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://github.com/backstage/backstage/tree/master/plugins/graphiql#readme
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
