apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-orchestrator
  title: "@red-hat-developer-hub/backstage-plugin-orchestrator"
  description: Frontend plugin for the Workflow Orchestrator, providing pages and entity content to run and manage workflows.
  tags:
    - frontend-plugin
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/orchestrator/plugins/orchestrator
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 6.2.0
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: redhat-developer
