apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-codescene
  title: "@backstage-community/plugin-codescene"
  description: Frontend plugin listing CodeScene projects and showing their code health analysis data.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/codescene/plugins/codescene
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.21.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
