apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parsifal-m-backstage-plugin-open-feedback-common
  title: "@parsifal-m/backstage-plugin-open-feedback-common"
  description: Common functionalities for the open-feedback plugin
  tags:
    - common-library
    - repo-backstage-open-feedback
  annotations:
    github.com/project-slug: Parsifal-M/backstage-open-feedback
    backstage.io/source-location: url:https://github.com/Parsifal-M/backstage-open-feedback/tree/HEAD/plugins/open-feedback-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.4.4
  links:
    - url: https://github.com/Parsifal-M/backstage-open-feedback
      title: GitHub repository
      icon: github
spec:
  type: common-library
  lifecycle: unknown
  owner: parsifal-m
