apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-kubernetes-cluster
  title: "@backstage/plugin-kubernetes-cluster"
  description: A Backstage plugin that shows details of Kubernetes clusters
  tags:
    - frontend-plugin
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/kubernetes-cluster
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.0.41-next.2
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
