apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadiehq-backstage-plugin-github-insights
  title: "@roadiehq/backstage-plugin-github-insights"
  description: Frontend plugin that shows GitHub repository contributors, languages, readme, and release widgets on entity pages.
  tags:
    - frontend-plugin
    - repo-roadie-backstage-plugins
  annotations:
    github.com/project-slug: RoadieHQ/roadie-backstage-plugins
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/HEAD/plugins/frontend/backstage-plugin-github-insights
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 3.5.0
  links:
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://roadie.io/backstage/plugins/github-insights/
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: roadiehq
