apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: veecode-platform-backstage-plugin-vee
  title: "@veecode-platform/backstage-plugin-vee"
  description: Frontend plugin providing an AI chat assistant interface backed by a configurable AI engine such as OpenAI.
  tags:
    - frontend-plugin
    - repo-platform-backstage-plugins
  annotations:
    github.com/project-slug: veecode-platform/platform-backstage-plugins
    backstage.io/source-location: url:https://github.com/veecode-platform/platform-backstage-plugins/tree/HEAD/plugins/vee
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.4.0
  links:
    - url: https://github.com/veecode-platform/platform-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: veecode-platform
