apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-quay
  title: "@backstage-community/plugin-scaffolder-backend-module-quay"
  description: The quay-actions module for @backstage-community/plugin-scaffolder-backend-module-quay
  tags:
    - backend-plugin-module
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/quay/plugins/quay-actions
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 2.22.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
