apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parsifal-m-plugin-opa-entity-checker
  title: "@parsifal-m/plugin-opa-entity-checker"
  description: Frontend plugin that checks catalog entities against Open Policy Agent policies and displays violation results on entity pages.
  tags:
    - frontend-plugin
    - repo-backstage-opa-plugins
  annotations:
    github.com/project-slug: Parsifal-M/backstage-opa-plugins
    backstage.io/source-location: url:https://github.com/Parsifal-M/backstage-opa-plugins/tree/HEAD/plugins/backstage-opa-entity-checker
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 2.1.0
  links:
    - url: https://github.com/Parsifal-M/backstage-opa-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: parsifal-m
