apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parseable-backstage-plugin-logstream
  title: "@parseable/backstage-plugin-logstream"
  description: Backstage plugin for integrating with Parseable log streams
  tags:
    - frontend-plugin
    - repo-backstage-plugin
  annotations:
    github.com/project-slug: parseablehq/backstage-plugin
    backstage.io/source-location: url:https://github.com/parseablehq/backstage-plugin/tree/HEAD/parseable-backstage-plugin/plugins/parseable-logstream
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.2.0
  links:
    - url: https://github.com/parseablehq/backstage-plugin
      title: GitHub repository
      icon: github
    - url: https://parseable.com
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: parseablehq
