apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terasky-backstage-plugin-kubernetes-resources-common
  title: "@terasky/backstage-plugin-kubernetes-resources-common"
  description: Common functionalities for the Kubernetes Resources plugin
  tags:
    - common-library
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: TeraSky-OSS/backstage-plugins
    backstage.io/source-location: url:https://github.com/TeraSky-OSS/backstage-plugins/tree/HEAD/plugins/kubernetes-resources-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.2.24
  links:
    - url: https://github.com/TeraSky-OSS/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://terasky.com
      title: Homepage
spec:
  type: common-library
  lifecycle: unknown
  owner: terasky-oss
