apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadiehq-backstage-plugin-jira
  title: "@roadiehq/backstage-plugin-jira"
  description: Frontend plugin showing Jira project overview, activity stream, and JQL query results on entity and home pages.
  tags:
    - frontend-plugin
    - repo-roadie-backstage-plugins
  annotations:
    github.com/project-slug: RoadieHQ/roadie-backstage-plugins
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/HEAD/plugins/frontend/backstage-plugin-jira
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 2.14.0
  links:
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://roadie.io/backstage/plugins/jira/
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: roadiehq
