apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: seatgeek-backstage-plugin-gitlab-catalog-backend
  title: "@seatgeek/backstage-plugin-gitlab-catalog-backend"
  description: Backend plugin that enriches Backstage catalog User entities with data from the GitLab API.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: seatgeek/backstage-plugins
    backstage.io/source-location: url:https://github.com/seatgeek/backstage-plugins/tree/HEAD/plugins/gitlab-catalog-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.0.0-semantically-released
  links:
    - url: https://github.com/seatgeek/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: seatgeek
