apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-stack-overflow
  title: "@backstage-community/plugin-stack-overflow"
  description: Frontend plugin that surfaces Stack Overflow questions and answers in Backstage search results and on the homepage.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/stack-overflow/plugins/stack-overflow
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.21.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
