apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-bazaar-backend
  title: "@backstage-community/plugin-bazaar-backend"
  description: Backend plugin that stores and serves project data for the Bazaar inner-source marketplace.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/bazaar/plugins/bazaar-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.27.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
