apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terasky-backstage-plugin-crossplane-resources-frontend
  title: "@terasky/backstage-plugin-crossplane-resources-frontend"
  description: Frontend plugin that shows a component's Crossplane claim, composite resource, and managed resources with YAML and graph views.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: TeraSky-OSS/backstage-plugins
    backstage.io/source-location: url:https://github.com/TeraSky-OSS/backstage-plugins/tree/HEAD/plugins/crossplane-resources
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 2.20.0
  links:
    - url: https://github.com/TeraSky-OSS/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://terasky.com
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: terasky-oss
