apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openchoreo-backstage-plugin-openchoreo-workflows-backend
  title: "@openchoreo/backstage-plugin-openchoreo-workflows-backend"
  description: Backend plugin supporting OpenChoreo generic workflow functionality.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: openchoreo/backstage-plugins
    backstage.io/source-location: url:https://github.com/openchoreo/backstage-plugins/tree/HEAD/plugins/openchoreo-workflows-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.2.0
  links:
    - url: https://github.com/openchoreo/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: openchoreo
