apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-azure-storage
  title: backstage-plugin-azure-storage
  description: Frontend plugin for browsing, navigating and downloading blobs in an Azure Storage account.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: deepan10/backstage-plugins
    backstage.io/source-location: url:https://github.com/deepan10/backstage-plugins/tree/HEAD/plugins/azure-storage
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.1.1
  links:
    - url: https://github.com/deepan10/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: deepan10
