apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-periskop
  title: "@backstage-community/plugin-periskop"
  description: Frontend plugin that displays aggregated exception and error data from a Periskop instance on catalog entity pages.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/periskop/plugins/periskop
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.21.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://periskop.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
