apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadiehq-catalog-backend-module-aws
  title: "@roadiehq/catalog-backend-module-aws"
  description: A set of Backstage catalog providers for AWS
  tags:
    - backend-plugin-module
    - repo-roadie-backstage-plugins
  annotations:
    github.com/project-slug: RoadieHQ/roadie-backstage-plugins
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/HEAD/plugins/backend/catalog-backend-module-aws
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 5.11.0
  links:
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://roadie.io
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: roadiehq
