apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-analytics-module-adoptio
  title: red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights
  description: Frontend module that reports adoption insights analytics events in Red Hat Developer Hub.
  tags:
    - frontend-plugin-module
    - repo-kuadrant-backstage-plugin
  annotations:
    github.com/project-slug: Kuadrant/kuadrant-backstage-plugin
    backstage.io/source-location: url:https://github.com/Kuadrant/kuadrant-backstage-plugin/tree/HEAD/dynamic-plugins/wrappers/red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights-dynamic
    backstage-plugins.io/role: frontend-plugin-module
    backstage-plugins.io/package-version: 0.8.2
  links:
    - url: https://github.com/Kuadrant/kuadrant-backstage-plugin
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: frontend-plugin-module
  lifecycle: unknown
  owner: kuadrant
