apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web-seven-backstage-plugin-scaffolder-extensions
  title: "@web-seven/backstage-plugin-scaffolder-extensions"
  description: Frontend plugin providing scaffolder field extensions that enhance the EntityPicker field and preview selected entities in templates.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: web-seven/backstage-plugins
    backstage.io/source-location: url:https://github.com/web-seven/backstage-plugins/tree/HEAD/plugins/plugin-scaffolder-extensions
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.0.25
  links:
    - url: https://github.com/web-seven/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: web-seven
