apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terasky-backstage-plugin-frontend-extensions-explorer
  title: "@terasky/backstage-plugin-frontend-extensions-explorer"
  description: Frontend Extensions Explorer Plugin for Backstage - visualize and inspect New Frontend System extensions
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: TeraSky-OSS/backstage-plugins
    backstage.io/source-location: url:https://github.com/TeraSky-OSS/backstage-plugins/tree/HEAD/plugins/frontend-extensions-explorer
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.7.0
  links:
    - url: https://github.com/TeraSky-OSS/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://terasky.com
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: terasky-oss
