apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadiehq-backstage-plugin-aws-lambda
  title: "@roadiehq/backstage-plugin-aws-lambda"
  description: Frontend plugin that shows an AWS Lambda function overview card on entity pages.
  tags:
    - frontend-plugin
    - repo-roadie-backstage-plugins
  annotations:
    github.com/project-slug: RoadieHQ/roadie-backstage-plugins
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/HEAD/plugins/frontend/backstage-plugin-aws-lambda
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 2.4.0
  links:
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://roadie.io/backstage/plugins/aws-lambda/
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: roadiehq
