apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: seatgeek-backstage-plugin-awards-common
  title: "@seatgeek/backstage-plugin-awards-common"
  description: Shared package providing common types and utilities used by the awards frontend and backend plugins.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: seatgeek/backstage-plugins
    backstage.io/source-location: url:https://github.com/seatgeek/backstage-plugins/tree/HEAD/plugins/awards-common
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.0.0-semantically-released
  links:
    - url: https://github.com/seatgeek/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: seatgeek
