apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kyverno-backstage-plugin-policy-reporter
  title: "@kyverno/backstage-plugin-policy-reporter"
  description: Frontend plugin that displays Kyverno policy reports from Policy Reporter for Backstage catalog entities.
  tags:
    - frontend-plugin
    - repo-backstage-policy-reporter-plugin
  annotations:
    github.com/project-slug: kyverno/backstage-policy-reporter-plugin
    backstage.io/source-location: url:https://github.com/kyverno/backstage-policy-reporter-plugin/tree/HEAD/plugins/policy-reporter
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 2.10.0
  links:
    - url: https://github.com/kyverno/backstage-policy-reporter-plugin
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: kyverno
