apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-explore
  title: "@backstage-community/plugin-explore"
  description: A Backstage plugin for building an exploration page of your software ecosystem
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/explore/plugins/explore
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.0.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
