apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: allegro-backstage-plugin-chat-bot-common
  title: "@allegro/backstage-plugin-chat-bot-common"
  description: Common functionalities for the chat-bot plugin
  tags:
    - common-library
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: allegro/backstage-plugins
    backstage.io/source-location: url:https://github.com/allegro/backstage-plugins/tree/HEAD/plugins/chat-bot/chat-bot-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.1.1
  links:
    - url: https://github.com/allegro/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: common-library
  lifecycle: unknown
  owner: allegro
