apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-jfrog-artifactory-libs
  title: backstage-plugin-jfrog-artifactory-libs
  description: Frontend plugin that displays JFrog Artifactory library details and lets users copy dependency definitions for Maven, npm, Docker, and other package managers.
  tags:
    - frontend-plugin
    - repo-backstage-jfrog-artifactory-libs
  annotations:
    github.com/project-slug: Vity01/backstage-jfrog-artifactory-libs
    backstage.io/source-location: url:https://github.com/Vity01/backstage-jfrog-artifactory-libs/tree/HEAD
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.0.12
  links:
    - url: https://github.com/Vity01/backstage-jfrog-artifactory-libs
      title: GitHub repository
      icon: github
    - url: https://github.com/Vity01/backstage-jfrog-artifactory-libs/
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: vity01
