apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: proberaum-backstage-plugin-assets
  title: "@proberaum/backstage-plugin-assets"
  description: Frontend plugin for managing and displaying assets within Backstage.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: proberaum/backstage-plugins
    backstage.io/source-location: url:https://github.com/proberaum/backstage-plugins/tree/HEAD/workspaces/assets/plugins/assets
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.7.0
  links:
    - url: https://github.com/proberaum/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: proberaum
