apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-signals
  title: "@backstage/plugin-signals"
  description: Frontend plugin that lets backend plugins publish real-time messages to subscribed frontend plugins.
  tags:
    - frontend-plugin
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/signals
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.0.35-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
