apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: veecode-platform-plugin-kong-service-manager-react
  title: "@veecode-platform/plugin-kong-service-manager-react"
  description: Web library of React components supporting the Kong Service Manager Backstage plugin.
  tags:
    - web-library
    - repo-platform-backstage-plugins
  annotations:
    github.com/project-slug: veecode-platform/platform-backstage-plugins
    backstage.io/source-location: url:https://github.com/veecode-platform/platform-backstage-plugins/tree/HEAD/packages/kong-service-manager-react
    backstage-plugins.io/role: web-library
    backstage-plugins.io/package-version: 0.1.1
  links:
    - url: https://github.com/veecode-platform/platform-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: web-library
  lifecycle: unknown
  owner: veecode-platform
