apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-report-portal
  title: "@backstage-community/plugin-report-portal"
  description: Frontend plugin that shows ReportPortal test automation projects and launches within Backstage.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/report-portal/plugins/report-portal
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.6.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
