apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-tech-radar
  title: "@backstage-community/plugin-tech-radar"
  description: A Backstage plugin that lets you display a Tech Radar for your organization
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/tech-radar/plugins/tech-radar
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.22.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
