apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-adoption-insights-common
  title: "@red-hat-developer-hub/backstage-plugin-adoption-insights-common"
  description: Common functionalities for the adoption-insights plugin
  tags:
    - common-library
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/adoption-insights/plugins/adoption-insights-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 1.0.1
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: common-library
  lifecycle: unknown
  owner: redhat-developer
