apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-backstage-plugin-catalog-backend-module-mta
  title: "@backstage-community/backstage-plugin-catalog-backend-module-mta-entity-provider"
  description: The mta-entity-provider backend module for the catalog plugin.
  tags:
    - backend-plugin-module
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/mta/plugins/catalog-backend-module-mta-entity-provider
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.4.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
