apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-entity-validation
  title: "@backstage-community/plugin-entity-validation"
  description: Frontend plugin adding a page where users can validate catalog entities.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/entity-validation/plugins/entity-validation
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.23.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
