apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-genai-plugin-langgraph-agent-for-backstage
  title: "@aws/genai-plugin-langgraph-agent-for-backstage"
  description: LangGraph agent module package for the GenAI AWS plugins for Backstage
  tags:
    - backend-plugin-module
    - repo-backstage-plugins-for-aws
  annotations:
    github.com/project-slug: awslabs/backstage-plugins-for-aws
    backstage.io/source-location: url:https://github.com/awslabs/backstage-plugins-for-aws/tree/HEAD/plugins/genai/agent-langgraph
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.8.0
  links:
    - url: https://github.com/awslabs/backstage-plugins-for-aws
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: awslabs
