apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gluo-nv-backstage-plugin-hetzner-backend
  title: "@gluo-nv/backstage-plugin-hetzner-backend"
  description: Backstage backend plugin for Hetzner Cloud integration.
  tags:
    - backend-plugin
    - repo-backstage-plugin-hetzner-backend
  annotations:
    github.com/project-slug: gluobe/backstage-plugin-hetzner-backend
    backstage.io/source-location: url:https://github.com/gluobe/backstage-plugin-hetzner-backend/tree/HEAD
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.1.1
  links:
    - url: https://github.com/gluobe/backstage-plugin-hetzner-backend
      title: GitHub repository
      icon: github
    - url: https://github.com/gluobe/hetzner-backstage-plugin
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: gluobe
