apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-search-backend-module-github-discuss
  title: "@backstage-community/plugin-search-backend-module-github-discussions"
  description: The github-discussions backend module for the search plugin.
  tags:
    - backend-plugin-module
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/github/plugins/search-backend-module-github-discussions
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.15.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
