apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-growthbook-backend
  title: "@backstage-community/plugin-growthbook-backend"
  description: Backend plugin proxying the GrowthBook management/SDK API and caching feature flags and projects for the frontend plugin.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/growthbook-flags/plugins/growthbook-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.1.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
