apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-multi-source-security-viewer-common
  title: "@backstage-community/plugin-multi-source-security-viewer-common"
  description: Common functionalities for the multi-source-security-viewer plugin
  tags:
    - common-library
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/multi-source-security-viewer/plugins/multi-source-security-viewer-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.16.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: common-library
  lifecycle: unknown
  owner: backstage
