apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-adoption-insights-back-2
  title: "@red-hat-developer-hub/backstage-plugin-adoption-insights-backend"
  description: Backend plugin that stores analytics events in a database and exposes an API layer for the Adoption Insights frontend.
  tags:
    - backend-plugin
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/adoption-insights/plugins/adoption-insights-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.0.1
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: redhat-developer
