apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terasky-backstage-plugin-vcfa-vks-cluster-provider
  title: "@terasky/backstage-plugin-vcfa-vks-cluster-provider"
  description: Backstage Kubernetes cluster supplier for VCF Automation VKS clusters
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: TeraSky-OSS/backstage-plugins
    backstage.io/source-location: url:https://github.com/TeraSky-OSS/backstage-plugins/tree/HEAD/plugins/vcfa-vks-cluster-provider
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.7.0
  links:
    - url: https://github.com/TeraSky-OSS/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://terasky.com
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: terasky-oss
