apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-auth-backend-module-oauth2-provider
  title: "@backstage/plugin-auth-backend-module-oauth2-provider"
  description: The oauth2-provider backend module for the auth plugin.
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/auth-backend-module-oauth2-provider
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.4.19-next.0
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
