apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emerchalegre-plugin-codacy-backend
  title: "@emerchalegre/plugin-codacy-backend"
  description: Backend plugin scaffolded with the Backstage CLI that serves the Codacy plugin's backend API.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: emerchalegre/backstage-plugins
    backstage.io/source-location: url:https://github.com/emerchalegre/backstage-plugins/tree/HEAD/plugins/codacy-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.1.0
  links:
    - url: https://github.com/emerchalegre/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: emerchalegre
