apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: plugin-aws-ecr-scan-backend
  title: plugin-aws-ecr-scan-backend
  description: Backend plugin scaffold supporting the AWS ECR scan frontend plugin.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: blakeromano/backstage-plugins
    backstage.io/source-location: url:https://github.com/blakeromano/backstage-plugins/tree/HEAD/plugins/aws-ecr-scan-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.1.0
  links:
    - url: https://github.com/blakeromano/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: blakeromano
