apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-sonarqube-react
  title: "@backstage-community/plugin-sonarqube-react"
  description: Shared React library of types and hooks used by the SonarQube frontend plugin.
  tags:
    - web-library
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/sonarqube/plugins/sonarqube-react
    backstage-plugins.io/role: web-library
    backstage-plugins.io/package-version: 1.2.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: web-library
  lifecycle: unknown
  owner: backstage
