apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-azure-sites-backend
  title: "@backstage-community/plugin-azure-sites-backend"
  description: Backend plugin that proxies requests to the Azure Portal API via the Azure SDK for the Azure Sites frontend plugin.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/azure-sites/plugins/azure-sites-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.16.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
