apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harnessio-backstage-plugin-harness-srm
  title: "@harnessio/backstage-plugin-harness-srm"
  description: Frontend plugin that displays Harness Service Reliability Management monitored services on entity pages.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: harness/backstage-plugins
    backstage.io/source-location: url:https://github.com/harness/backstage-plugins/tree/HEAD/plugins/harness-srm
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.3.0
  links:
    - url: https://github.com/harness/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: harness
