apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-auth-backend-module-aws-alb-provider
  title: "@backstage/plugin-auth-backend-module-aws-alb-provider"
  description: The aws-alb provider module for the Backstage auth backend.
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/auth-backend-module-aws-alb-provider
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.4.20-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
