apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-scaffolder-backend-module-workspace-database
  title: "@backstage/plugin-scaffolder-backend-module-workspace-database"
  description: Database workspace provider module for @backstage/plugin-scaffolder-backend (development use only)
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/scaffolder-backend-module-workspace-database
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.1.0-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
