apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apic-backstage
  title: apic-backstage
  description: The APIC backend module for the catalog plugin.
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: ibm-apiconnect/backstage
    backstage.io/source-location: url:https://github.com/ibm-apiconnect/backstage/tree/HEAD/plugins/apic-backstage
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 1.0.3
  links:
    - url: https://github.com/ibm-apiconnect/backstage
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: ibm-apiconnect
