apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-signals-2
  title: backstage-plugin-signals
  description: Frontend plugin that provides real-time signal subscriptions for Backstage.
  tags:
    - frontend-plugin
    - repo-kuadrant-backstage-plugin
  annotations:
    github.com/project-slug: Kuadrant/kuadrant-backstage-plugin
    backstage.io/source-location: url:https://github.com/Kuadrant/kuadrant-backstage-plugin/tree/HEAD/dynamic-plugins/wrappers/backstage-plugin-signals
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.0.29
  links:
    - url: https://github.com/Kuadrant/kuadrant-backstage-plugin
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: kuadrant
