apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-notifications-backend-module-slack
  title: "@backstage/plugin-notifications-backend-module-slack"
  description: The slack backend module for the notifications plugin.
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/notifications-backend-module-slack
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.4.6-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
