apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-fairwinds-insights
  title: "@backstage-community/plugin-fairwinds-insights"
  description: Frontend plugin showing Fairwinds Insights vulnerabilities, cost, action items and resource history for linked catalog entities.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/fairwinds-insights/plugins/fairwinds-insights
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.5.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
