apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-org-react
  title: "@backstage/plugin-org-react"
  description: Web library providing a GroupListPicker autocomplete component for selecting catalog groups.
  tags:
    - web-library
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/org-react
    backstage-plugins.io/role: web-library
    backstage-plugins.io/package-version: 0.1.54-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: web-library
  lifecycle: unknown
  owner: backstage
