apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: immobiliarelabs-backstage-plugin-gitlab
  title: "@immobiliarelabs/backstage-plugin-gitlab"
  description: Frontend plugin that displays GitLab pipeline status, merge requests, and issue information on entity pages.
  tags:
    - frontend-plugin
    - repo-backstage-plugin-gitlab
  annotations:
    github.com/project-slug: immobiliare/backstage-plugin-gitlab
    backstage.io/source-location: url:https://github.com/immobiliare/backstage-plugin-gitlab/tree/HEAD/packages/gitlab
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 7.0.1
  links:
    - url: https://github.com/immobiliare/backstage-plugin-gitlab
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: immobiliare
