apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-scaffolder-common
  title: "@backstage/plugin-scaffolder-common"
  description: Common functionalities for the scaffolder, to be shared between scaffolder and scaffolder-backend plugin
  tags:
    - common-library
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/scaffolder-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 2.3.0-next.2
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: common-library
  lifecycle: unknown
  owner: backstage
