apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-graphql-voyager
  title: "@backstage-community/plugin-graphql-voyager"
  description: Backstage plugin for GraphQL Voyager
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/graphql-voyager/plugins/graphql-voyager
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.20.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
