apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tssc-plugins-backstage-community-plugin-argocd-backend
  title: "@tssc-plugins/backstage-community-plugin-argocd-backend"
  description: Backend plugin providing ArgoCD integration APIs used by the frontend ArgoCD plugin.
  tags:
    - backend-plugin
    - repo-tssc-backstage-plugins
  annotations:
    github.com/project-slug: redhat-appstudio/tssc-backstage-plugins
    backstage.io/source-location: url:https://github.com/redhat-appstudio/tssc-backstage-plugins/tree/HEAD/plugins/argocd-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.0.1
  links:
    - url: https://github.com/redhat-appstudio/tssc-backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/trusted
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: redhat-appstudio
