apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-carbon-footprint-backstage-plugin-frontend
  title: "@cloud-carbon-footprint/backstage-plugin-frontend"
  description: The Backstage front-end plugin for Cloud Carbon Footprint.
  tags:
    - frontend-plugin
    - repo-ccf-backstage-plugin
  annotations:
    github.com/project-slug: cloud-carbon-footprint/ccf-backstage-plugin
    backstage.io/source-location: url:https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/tree/HEAD/plugins/frontend
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.1.1
  links:
    - url: https://github.com/cloud-carbon-footprint/ccf-backstage-plugin
      title: GitHub repository
      icon: github
    - url: https://www.cloudcarbonfootprint.org/
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: cloud-carbon-footprint
