apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-scaffolder-backend-module-sentry
  title: "@backstage/plugin-scaffolder-backend-module-sentry"
  description: Backend module adding scaffolder actions to create Sentry projects and fetch their DSNs.
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/scaffolder-backend-module-sentry
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.3.8-next.2
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
