apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-backend-module-ldap-2
  title: backstage-plugin-catalog-backend-module-ldap
  description: Catalog backend module that imports users and groups from an LDAP directory.
  tags:
    - backend-plugin-module
    - repo-kuadrant-backstage-plugin
  annotations:
    github.com/project-slug: Kuadrant/kuadrant-backstage-plugin
    backstage.io/source-location: url:https://github.com/Kuadrant/kuadrant-backstage-plugin/tree/HEAD/dynamic-plugins/wrappers/backstage-plugin-catalog-backend-module-ldap-dynamic
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.12.3
  links:
    - url: https://github.com/Kuadrant/kuadrant-backstage-plugin
      title: GitHub repository
      icon: github
    - url: https://red.ht/rhdh
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: kuadrant
