apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-search
  title: "@backstage/plugin-search"
  description: The Backstage plugin that provides your backstage app with search
  tags:
    - frontend-plugin
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/search
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.7.8-next.2
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
