apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-dcm-backend
  title: "@red-hat-developer-hub/backstage-plugin-dcm-backend"
  description: Backend plugin scaffolded with the Backstage CLI supporting the dcm frontend plugin; specific functionality undocumented.
  tags:
    - backend-plugin
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/dcm/plugins/dcm-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.0.0
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: redhat-developer
