apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-azure-devops-common
  title: "@backstage-community/plugin-azure-devops-common"
  description: Shared types and utilities used by the Azure DevOps frontend and backend plugins.
  tags:
    - common-library
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/azure-devops/plugins/azure-devops-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.26.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: common-library
  lifecycle: unknown
  owner: backstage
