apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: veecode-platform-backstage-plugin-gitlab-pipelines
  title: "@veecode-platform/backstage-plugin-gitlab-pipelines"
  description: Frontend plugin integrating GitLab CI, letting users view, run, and cancel pipelines and jobs from a catalog component.
  tags:
    - frontend-plugin
    - repo-platform-backstage-plugins
  annotations:
    github.com/project-slug: veecode-platform/platform-backstage-plugins
    backstage.io/source-location: url:https://github.com/veecode-platform/platform-backstage-plugins/tree/HEAD/plugins/gitlab-pipelines
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.7.0
  links:
    - url: https://github.com/veecode-platform/platform-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: veecode-platform
