apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dweber019-backstage-plugin-api-docs-spectral-linter
  title: "@dweber019/backstage-plugin-api-docs-spectral-linter"
  description: Frontend plugin that lints API definitions against Spectral rule sets on the entity API docs page.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: dweber019/backstage-plugins
    backstage.io/source-location: url:https://github.com/dweber019/backstage-plugins/tree/HEAD/plugins/api-docs-spectral-linter
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.5.2
  links:
    - url: https://github.com/dweber019/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://github.com/dweber019/backstage-plugins/tree/main/plugins/api-docs-spectral-linter
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: dweber019
