apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terasky-backstage-plugin-spectrocloud-auth
  title: "@terasky/backstage-plugin-spectrocloud-auth"
  description: SpectroCloud authentication frontend plugin for Backstage
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: TeraSky-OSS/backstage-plugins
    backstage.io/source-location: url:https://github.com/TeraSky-OSS/backstage-plugins/tree/HEAD/plugins/spectrocloud-auth
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.12.0
  links:
    - url: https://github.com/TeraSky-OSS/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://terasky.com
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: terasky-oss
