apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-ocm
  title: "@backstage-community/plugin-ocm"
  description: Frontend plugin that integrates Open Cluster Management (OCM), importing managed clusters into the catalog and showing real-time cluster status.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/ocm/plugins/ocm
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 5.21.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
