apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: veecode-platform-plugin-kong-service-manager-backend
  title: "@veecode-platform/plugin-kong-service-manager-backend"
  description: Backend plugin providing API endpoints for managing Kong services, routes, and plugins used by the Kong Service Manager frontend plugin.
  tags:
    - backend-plugin
    - repo-platform-backstage-plugins
  annotations:
    github.com/project-slug: veecode-platform/platform-backstage-plugins
    backstage.io/source-location: url:https://github.com/veecode-platform/platform-backstage-plugins/tree/HEAD/plugins/kong-service-manager-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.4.1
  links:
    - url: https://github.com/veecode-platform/platform-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: veecode-platform
