apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dweber019-backstage-plugin-relations
  title: "@dweber019/backstage-plugin-relations"
  description: Frontend plugin that improves visualization of custom catalog relations, including catalog graph card wrappers.
  tags:
    - frontend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: dweber019/backstage-plugins
    backstage.io/source-location: url:https://github.com/dweber019/backstage-plugins/tree/HEAD/plugins/relations
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.1.2
  links:
    - url: https://github.com/dweber019/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://github.com/dweber019/backstage-plugins/tree/main/plugins/relations
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: dweber019
