apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-npm-backend
  title: "@backstage-community/plugin-npm-backend"
  description: Plugin that shows npm registry information, release history, and version tags for catalog entities.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/npm/plugins/npm-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.25.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://github.com/backstage/community-plugins/tree/main/workspaces/npm/plugins/npm-backend
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
