apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: veecode-platform-backstage-plugin-github-workflows
  title: "@veecode-platform/backstage-plugin-github-workflows"
  description: Frontend plugin for manually triggering and listing GitHub Actions workflows from a catalog component.
  tags:
    - frontend-plugin
    - repo-platform-backstage-plugins
  annotations:
    github.com/project-slug: veecode-platform/platform-backstage-plugins
    backstage.io/source-location: url:https://github.com/veecode-platform/platform-backstage-plugins/tree/HEAD/plugins/github-workflows
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.2.3
  links:
    - url: https://github.com/veecode-platform/platform-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: veecode-platform
