apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-techdocs-backend
  title: "@backstage/plugin-techdocs-backend"
  description: The Backstage backend plugin that renders technical documentation for your components
  tags:
    - backend-plugin
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/techdocs-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 2.3.0-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
