apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-azure-sites
  title: "@backstage-community/plugin-azure-sites"
  description: Frontend plugin showing the status of Azure Sites (Apps and Functions) on entity pages, with links to Azure overview and logs.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/azure-sites/plugins/azure-sites
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.13.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
