apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-catalog-backend-module-mend-entity-p
  title: "@backstage-community/plugin-catalog-backend-module-mend-entity-processor"
  description: The mend-entity-processor backend module for the catalog plugin.
  tags:
    - backend-plugin-module
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/mend/plugins/catalog-backend-module-mend-entity-processor
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.2.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
