apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-argocd-backend
  title: "@backstage-community/plugin-argocd-backend"
  description: Backend plugin that integrates Backstage with ArgoCD instances to monitor applications.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/argocd/plugins/argocd-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.7.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
