apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-tekton-react
  title: "@backstage-community/plugin-tekton-react"
  description: Web library for the tekton plugin
  tags:
    - web-library
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/tekton/plugins/tekton-react
    backstage-plugins.io/role: web-library
    backstage-plugins.io/package-version: 0.9.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: web-library
  lifecycle: unknown
  owner: backstage
