apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emma-community-backstage-plugin-emma-backend
  title: "@emma-community/backstage-plugin-emma-backend"
  description: Backend for the emma plugin
  tags:
    - backend-plugin
    - repo-emma-backstage-plugins
  annotations:
    github.com/project-slug: emma-community/emma-backstage-plugins
    backstage.io/source-location: url:https://github.com/emma-community/emma-backstage-plugins/tree/HEAD/plugins/emma-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.1.9
  links:
    - url: https://github.com/emma-community/emma-backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://emma.ms
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: emma-community
