apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terasky-backstage-plugin-scaffolder-backend-module-spring-initi
  title: "@terasky/backstage-plugin-scaffolder-backend-module-spring-initializer"
  description: The spring-initializer module for @backstage/plugin-scaffolder-backend
  tags:
    - backend-plugin-module
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: TeraSky-OSS/backstage-plugins
    backstage.io/source-location: url:https://github.com/TeraSky-OSS/backstage-plugins/tree/HEAD/plugins/scaffolder-backend-module-spring-initializer
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.8.0
  links:
    - url: https://github.com/TeraSky-OSS/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://terasky.com
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: terasky-oss
