apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-home-react
  title: "@backstage/plugin-home-react"
  description: A Backstage plugin that contains react components helps you build a home page
  tags:
    - web-library
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/home-react
    backstage-plugins.io/role: web-library
    backstage-plugins.io/package-version: 0.1.42-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://github.com/backstage/backstage/tree/master/plugins/home-react#readme
      title: Homepage
spec:
  type: web-library
  lifecycle: unknown
  owner: backstage
