apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scalr-io-backstage-plugin-scalr-backend
  title: "@scalr-io/backstage-plugin-scalr-backend"
  description: Backend plugin that integrates Scalr with the Backstage backend for the Scalr frontend plugin.
  tags:
    - backend-plugin
    - repo-scalr-backstage-plugin
  annotations:
    github.com/project-slug: Scalr/scalr-backstage-plugin
    backstage.io/source-location: url:https://github.com/Scalr/scalr-backstage-plugin/tree/HEAD/plugins/scalr-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.4.0
  links:
    - url: https://github.com/Scalr/scalr-backstage-plugin
      title: GitHub repository
      icon: github
    - url: https://www.scalr.com
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: scalr
