apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-ocm-backend
  title: "@backstage-community/plugin-ocm-backend"
  description: Backend that connects Backstage to Open Cluster Management (OCM) and discovers managed clusters for the catalog.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/ocm/plugins/ocm-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 5.21.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
