apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-proxy-node
  title: "@backstage/plugin-proxy-node"
  description: The plugin-proxy-node module for @backstage/plugin-proxy-backend
  tags:
    - node-library
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/proxy-node
    backstage-plugins.io/role: node-library
    backstage-plugins.io/package-version: 0.1.19-next.0
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: node-library
  lifecycle: unknown
  owner: backstage
