apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-checkmarx
  title: "@backstage-community/plugin-checkmarx"
  description: Backstage frontend plugin for displaying Checkmarx scan data on catalog entities
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/checkmarx/plugins/checkmarx
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.0.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
