apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: veecode-platform-backstage-plugin-kubernetes-gpt-analyzer
  title: "@veecode-platform/backstage-plugin-kubernetes-gpt-analyzer"
  description: Frontend plugin using k8sgpt AI analysis to surface Kubernetes error diagnostics and suggested fixes for a component.
  tags:
    - frontend-plugin
    - repo-platform-backstage-plugins
  annotations:
    github.com/project-slug: veecode-platform/platform-backstage-plugins
    backstage.io/source-location: url:https://github.com/veecode-platform/platform-backstage-plugins/tree/HEAD/plugins/kubernetes-gpt-analyzer
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.2.0
  links:
    - url: https://github.com/veecode-platform/platform-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: veecode-platform
