apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: red-hat-developer-hub-backstage-plugin-catalog-techdoc-url-read
  title: "@red-hat-developer-hub/backstage-plugin-catalog-techdoc-url-reader-backend"
  description: Backend plugin implementing a URL Reader that lets TechDocs fetch AI model card content from the RHDH Model Catalog Bridge.
  tags:
    - backend-plugin
    - repo-rhdh-plugins
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/HEAD/workspaces/ai-integrations/plugins/catalog-techdoc-url-reader-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.6.3
  links:
    - url: https://github.com/redhat-developer/rhdh-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: redhat-developer
