apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-home
  title: "@backstage/plugin-home"
  description: A Backstage plugin that helps you build a home page
  tags:
    - frontend-plugin
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/home
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.9.10-next.2
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://github.com/backstage/backstage/tree/master/plugins/home#readme
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
