apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pagerduty-backstage-plugin-scaffolder-actions
  title: "@pagerduty/backstage-plugin-scaffolder-actions"
  description: Backend module providing a scaffolder action to create PagerDuty services from Software Templates.
  tags:
    - backend-plugin-module
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: PagerDuty/backstage-plugins
    backstage.io/source-location: url:https://github.com/PagerDuty/backstage-plugins/tree/HEAD/plugins/backstage-plugin-scaffolder-actions
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.3.1
  links:
    - url: https://github.com/PagerDuty/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://pagerduty.github.io/backstage-plugin-docs/index.html
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: pagerduty
