apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-techdocs-addons-test-utils
  title: "@backstage/plugin-techdocs-addons-test-utils"
  description: Web library of testing utilities for developing TechDocs addons.
  tags:
    - web-library
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/techdocs-addons-test-utils
    backstage-plugins.io/role: web-library
    backstage-plugins.io/package-version: 2.0.9-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: web-library
  lifecycle: unknown
  owner: backstage
