apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-apollo-explorer
  title: "@backstage-community/plugin-apollo-explorer"
  description: Frontend plugin that embeds an Apollo GraphQL graph explorer into Backstage.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/apollo-explorer/plugins/apollo-explorer
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.24.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
