apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-backstage-plugin-opa-demo-backend
  title: "@internal/backstage-plugin-opa-demo-backend"
  description: Backend demo plugin showing how to use the opa-node library's OpaService to authorize backend plugin endpoints.
  tags:
    - backend-plugin
    - repo-backstage-opa-plugins
  annotations:
    github.com/project-slug: Parsifal-M/backstage-opa-plugins
    backstage.io/source-location: url:https://github.com/Parsifal-M/backstage-opa-plugins/tree/HEAD/plugins/opa-demo-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.1.2
  links:
    - url: https://github.com/Parsifal-M/backstage-opa-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: parsifal-m
