apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-growthbook
  title: "@backstage-community/plugin-growthbook"
  description: Frontend plugin to view and manage GrowthBook feature flags on catalog entities.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/growthbook-flags/plugins/growthbook
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.1.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
