apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-auth-backend-module-keycloak-provide
  title: "@backstage-community/plugin-auth-backend-module-keycloak-provider"
  description: Backend auth module enabling Backstage sign-in via Keycloak using OpenID Connect.
  tags:
    - backend-plugin-module
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/keycloak/plugins/auth-backend-module-keycloak
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.5.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
