apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: statefulhq-backstage-plugin-stateful-backend
  title: "@statefulhq/backstage-plugin-stateful-backend"
  description: Example backend plugin scaffolded via the Backstage CLI exposing a health API endpoint for the Stateful integration.
  tags:
    - backend-plugin
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: stateful/backstage-plugins
    backstage.io/source-location: url:https://github.com/stateful/backstage-plugins/tree/HEAD/plugins/stateful-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 1.0.0
  links:
    - url: https://github.com/stateful/backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: stateful
