apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-github-issues
  title: "@backstage-community/plugin-github-issues"
  description: Frontend plugin listing open GitHub issues for a catalog entity based on its GitHub project-slug annotation.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/github/plugins/github-issues
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 1.3.2
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
