apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: forgedapps-backstage-catalog-webhook-plugin
  title: "@forgedapps/backstage-catalog-webhook-plugin"
  description: Publish a Backstage catalog to a remote webhook. Designed by Forged Apps to synchronize Backstage with Atlassian Compass, but it can be used to push your catalog to any HTTP endpoint.
  tags:
    - backend-plugin-module
    - repo-backstage-catalog-webhook-plugin
  annotations:
    github.com/project-slug: ForgedApps/backstage-catalog-webhook-plugin
    backstage.io/source-location: url:https://github.com/ForgedApps/backstage-catalog-webhook-plugin/tree/HEAD
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 3.5.1
  links:
    - url: https://github.com/ForgedApps/backstage-catalog-webhook-plugin
      title: GitHub repository
      icon: github
    - url: https://github.com/forgedapps/backstage-catalog-webhook-plugin#readme
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: forgedapps
