apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: humanitec-backstage-plugin-common
  title: "@humanitec/backstage-plugin-common"
  description: Humanitec API Client
  tags:
    - common-library
    - repo-humanitec-backstage-plugins
  annotations:
    github.com/project-slug: humanitec/humanitec-backstage-plugins
    backstage.io/source-location: url:https://github.com/humanitec/humanitec-backstage-plugins/tree/HEAD/plugins/humanitec-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.7.6
  links:
    - url: https://github.com/humanitec/humanitec-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: common-library
  lifecycle: unknown
  owner: humanitec
