apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tssc-plugins-backstage-community-plugin-multi-source-security-v
  title: "@tssc-plugins/backstage-community-plugin-multi-source-security-viewer"
  description: Frontend plugin that displays security scan results from multiple sources for Backstage catalog entities.
  tags:
    - frontend-plugin
    - repo-tssc-backstage-plugins
  annotations:
    github.com/project-slug: redhat-appstudio/tssc-backstage-plugins
    backstage.io/source-location: url:https://github.com/redhat-appstudio/tssc-backstage-plugins/tree/HEAD/plugins/multi-source-security-viewer
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 0.9.0
  links:
    - url: https://github.com/redhat-appstudio/tssc-backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://red.ht/trusted
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: redhat-appstudio
