apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-backend-module-gitlab-org
  title: "@backstage/plugin-catalog-backend-module-gitlab-org"
  description: The gitlab-org backend module for the catalog plugin.
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/catalog-backend-module-gitlab-org
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.2.25-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
