apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-tech-insights-maturity-common
  title: "@backstage-community/plugin-tech-insights-maturity-common"
  description: Common functionalities for the tech-insights-maturity plugin
  tags:
    - common-library
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/tech-insights/plugins/tech-insights-maturity-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.7.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
spec:
  type: common-library
  lifecycle: unknown
  owner: backstage
