apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sbordeyne-plugin-catalog-backend-module-gcp-provider
  title: "@sbordeyne/plugin-catalog-backend-module-gcp-provider"
  description: The gcp-provider backend module for the catalog plugin.
  tags:
    - backend-plugin-module
    - repo-backstage-plugins
  annotations:
    github.com/project-slug: sbordeyne/backstage-plugins
    backstage.io/source-location: url:https://github.com/sbordeyne/backstage-plugins/tree/HEAD/plugins/catalog-backend-module-gcp-provider
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.3.2
  links:
    - url: https://github.com/sbordeyne/backstage-plugins
      title: GitHub repository
      icon: github
    - url: https://sbordeyne.github.io/backstage-plugins/dev/plugins/gcp-catalog-provider/
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: sbordeyne
