apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-backend-module-openapi
  title: "@backstage/plugin-catalog-backend-module-openapi"
  description: A Backstage catalog backend module that helps with OpenAPI specifications
  tags:
    - backend-plugin-module
    - repo-backstage
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/HEAD/plugins/catalog-backend-module-openapi
    backstage-plugins.io/role: backend-plugin-module
    backstage-plugins.io/package-version: 0.2.26-next.1
  links:
    - url: https://github.com/backstage/backstage
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin-module
  lifecycle: unknown
  owner: backstage
