apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: veecode-platform-backstage-plugin-vee-common
  title: "@veecode-platform/backstage-plugin-vee-common"
  description: Common functionalities for the veecode-assistant-ai plugin
  tags:
    - common-library
    - repo-platform-backstage-plugins
  annotations:
    github.com/project-slug: veecode-platform/platform-backstage-plugins
    backstage.io/source-location: url:https://github.com/veecode-platform/platform-backstage-plugins/tree/HEAD/plugins/vee-common
    backstage-plugins.io/role: common-library
    backstage-plugins.io/package-version: 0.5.0
  links:
    - url: https://github.com/veecode-platform/platform-backstage-plugins
      title: GitHub repository
      icon: github
spec:
  type: common-library
  lifecycle: unknown
  owner: veecode-platform
