apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-adr-backend
  title: "@backstage-community/plugin-adr-backend"
  description: Backend plugin that serves ADR documents and indexes them for Backstage Search.
  tags:
    - backend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/adr/plugins/adr-backend
    backstage-plugins.io/role: backend-plugin
    backstage-plugins.io/package-version: 0.25.1
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: backend-plugin
  lifecycle: unknown
  owner: backstage
