apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugin-mend
  title: "@backstage-community/plugin-mend"
  description: Frontend plugin that displays Mend.io project lists and security findings for catalog entities.
  tags:
    - frontend-plugin
    - repo-community-plugins
  annotations:
    github.com/project-slug: backstage/community-plugins
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/HEAD/workspaces/mend/plugins/mend
    backstage-plugins.io/role: frontend-plugin
    backstage-plugins.io/package-version: 2.1.0
  links:
    - url: https://github.com/backstage/community-plugins
      title: GitHub repository
      icon: github
    - url: https://backstage.io
      title: Homepage
spec:
  type: frontend-plugin
  lifecycle: unknown
  owner: backstage
